all:
	colorcc g++ -I/DLlocal/lazarv/git/boost/numeric_bindings -I/DLlocal/lazarv/bins/include -I. -llapack fundamentalLinear.cpp -o fundamentalLinear
#	colorcc g++ -g -I/DLlocal/lazarv/git/boost/numeric_bindings -I/DLlocal/lazarv/bins/include -I. -L/opt/local/lib/ -llapack fundamentalMatrix.cpp homographySVD.cpp -o homo
